#!/usr/bin/ruby

def factor(num)
	num.times do
		|time|
		val = time+2
		if val * val > num then
			return -1
		end
		if (num / val) * val == num then
			return val
		end
	end


end

File.open(ARGV[0], "r").each_line do
	|l|
	num = l.chomp.to_i
	f1 = factor(num)
	f2 = num / f1
	if f1 != -1 then
		puts num.to_s + "=" + f2.to_s + "*" + f1.to_s
	end
end
